trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: 'azure'
  resourceGroupName: 'example-resources'
  location: 'West Europe'

stages:
  - stage: Deploy
    jobs:
      - job: CreateResourceGroup
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating Resource Group: $(resourceGroupName)"
                az group create --name $(resourceGroupName) --location $(location)
